# Usa uma imagem oficial do Node.js leve (Alpine Linux)
FROM node:18-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copia os arquivos de definição de dependências primeiro
# Isso aproveita o cache do Docker se as dependências não mudarem
COPY package*.json ./

# Instala as dependências de produção
RUN npm install --production

# Copia o restante do código do projeto para o contêiner
COPY . .

# Comando padrão para iniciar o contêiner
# (Roda o seu script principal)
CMD [ "node", "main.js" ]